import {products,getProduct,money,productVisual,card,delivery} from './products.js';
const $=s=>document.querySelector(s); const cartKey='nubl-cart';
const readCart=()=>JSON.parse(localStorage.getItem(cartKey)||'[]'); const saveCart=c=>{localStorage.setItem(cartKey,JSON.stringify(c)); updateCount();};
const updateCount=()=>document.querySelectorAll('.cart-count').forEach(e=>e.textContent=readCart().reduce((n,i)=>n+i.qty,0));
const add=(id,size)=>{const c=readCart(),i=c.find(x=>x.id===id&&x.size===size);i?i.qty++:c.push({id,size,qty:1});saveCart(c);toast('تمت إضافة العطر إلى السلة');};
const remove=(id,size)=>saveCart(readCart().filter(x=>!(x.id===id&&x.size===size)));
const change=(id,size,delta)=>{const c=readCart(),i=c.find(x=>x.id===id&&x.size===size);if(i){i.qty+=delta;if(i.qty<1)return remove(id,size);}saveCart(c);renderCart();};
const toast=t=>{let e=$('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.append(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
const wireAdds=()=>document.querySelectorAll('.add-to-cart').forEach(b=>b.addEventListener('click',()=>add(b.dataset.id,b.dataset.size||getProduct(b.dataset.id).size)));
function renderHome(){const e=$('#featured-products');if(e)e.innerHTML=products.slice(0,4).map(card).join('');wireAdds();}
function renderProducts(){const e=$('#all-products');if(!e)return;const render=()=>{const q=($('#search').value||'').trim().toLowerCase(),type=$('#type-filter').value,size=$('#size-filter').value,price=$('#price-filter').value,stock=$('#stock-filter').value;const list=products.filter(p=>(!q||(p.name+p.arabicName+p.short).toLowerCase().includes(q))&&(!type||p.type===type)&&(!size||p.size===size)&&(!stock||p.stock===stock)&&(!price||(price==='0-150'?p.price<150:price==='150-250'?p.price>=150&&p.price<=250:p.price>250)));e.innerHTML=list.length?list.map(card).join(''):'<div class="empty-state"><h3>لم نجد عطراً بهذه المواصفات</h3><p>جرب تغيير كلمات البحث أو الفلاتر.</p></div>';$('#results-count').textContent=`عرض ${list.length} من ${products.length} عطور`;wireAdds()};['search','type-filter','size-filter','price-filter','stock-filter'].forEach(id=>$('#'+id).addEventListener('input',render));$('#clear-filters').addEventListener('click',()=>{['search','type-filter','size-filter','price-filter','stock-filter'].forEach(id=>$('#'+id).value='');render()});render();}
function renderDetail(){const e=$('#product-detail');if(!e)return;const p=getProduct(new URLSearchParams(location.search).get('id'))||products[0];e.innerHTML=`<div class="detail-media">${productVisual(p)}<div class="detail-seal">NUːBL<br><small>EST. 2024</small></div></div><div class="detail-copy"><a class="back-link" href="products.html">→ العودة إلى العطور</a><span class="eyebrow">${p.type} · ${p.stock}</span><h1>${p.name}</h1><h2>${p.arabicName}</h2><div class="detail-rating"><span>★★★★★</span> ${p.rating} (48 تقييم)</div><p class="detail-description">${p.description}</p><div class="notes">${p.notes.map(n=>`<span>${n}</span>`).join('')}</div><div class="detail-buy"><strong>${money(p.price)}</strong><span>${p.size}</span><div class="qty"><button data-q="-1">−</button><b id="qty">1</b><button data-q="1">+</button></div></div><div class="detail-actions"><button id="detail-add" class="btn btn-gold" ${p.stock!=='متوفر'?'disabled':''}>أضف إلى السلة</button><button id="detail-buy" class="btn btn-dark" ${p.stock!=='متوفر'?'disabled':''}>اشترِ الآن</button></div></div>`;let qty=1;document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{qty=Math.max(1,qty+Number(b.dataset.q));$('#qty').textContent=qty});$('#detail-add').onclick=()=>{for(let i=0;i<qty;i++)add(p.id,p.size)};$('#detail-buy').onclick=()=>{for(let i=0;i<qty;i++)add(p.id,p.size);location.href='cart.html'};}
function totals(){const items=readCart(),subtotal=items.reduce((n,i)=>n+(getProduct(i.id)?.price||0)*i.qty,0);const city=$('#city')?.value,ship=city==='casablanca'?delivery.casablanca:delivery.other;return {items,subtotal,ship,total:subtotal?subtotal+ship:0};}
function renderCart(){const e=$('#cart-content');if(!e)return;const {items,subtotal,ship,total}=totals();if(!items.length){e.innerHTML='<div class="empty-state"><div class="empty-icon">◇</div><h2>سلتك فارغة</h2><p>أضف عطراً يليق بك لتبدأ رحلتك.</p><a class="btn btn-gold" href="products.html">اكتشف العطور</a></div>';return}e.innerHTML=`<div class="cart-items"><div class="cart-title"><h2>منتجاتك</h2><span>${items.length} منتجات</span></div>${items.map(i=>{const p=getProduct(i.id);return `<article class="cart-item">${productVisual(p)}<div><h3>${p.name}</h3><p>${p.size} · ${money(p.price)}</p><div class="qty"><button data-change="-1" data-id="${p.id}" data-size="${i.size}">−</button><b>${i.qty}</b><button data-change="1" data-id="${p.id}" data-size="${i.size}">+</button></div></div><strong>${money(p.price*i.qty)}</strong><button class="remove" data-remove="1" data-id="${p.id}" data-size="${i.size}">حذف</button></article>`}).join('')}</div><aside class="summary"><h2>ملخص الطلب</h2><div><span>المجموع الفرعي</span><strong>${money(subtotal)}</strong></div><div><span>التوصيل</span><strong>${money(ship)}</strong></div><hr><div class="grand"><span>الإجمالي</span><strong>${money(total)}</strong></div><a class="btn btn-gold full" href="checkout.html">متابعة الطلب</a><p class="secure">✓ الدفع عند الاستلام متاح</p></aside>`;e.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>change(b.dataset.id,b.dataset.size,Number(b.dataset.change)));e.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{remove(b.dataset.id,b.dataset.size);renderCart()});}
function renderCheckout(){const e=$('#checkout-content');if(!e)return;const {items}=totals();if(!items.length){e.innerHTML='<div class="empty-state"><h2>السلة فارغة</h2><a class="btn btn-gold" href="products.html">العودة للتسوق</a></div>';return}e.innerHTML=`<form id="order-form" class="checkout-form"><div class="form-card"><h2>معلومات التوصيل</h2><div class="form-grid"><label>الاسم الكامل *<input required name="name" placeholder="مثال: محمد العلوي"></label><label>رقم الهاتف *<input required name="phone" type="tel" placeholder="06 00 00 00 00"></label><label>المدينة *<select required name="city" id="city"><option value="casablanca">الدار البيضاء</option><option value="other">مدينة أخرى</option></select></label><label>الحي *<input required name="district" placeholder="اسم الحي"></label><label class="wide">العنوان بالتفصيل *<textarea required name="address" rows="3" placeholder="الشارع، رقم المنزل..."></textarea></label><label class="wide">ملاحظات إضافية (اختياري)<textarea name="notes" rows="2"></textarea></label></div><h2>طريقة الدفع</h2><label class="payment-option"><input type="radio" checked> الدفع عند الاستلام <small>متاح حالياً</small></label><label class="payment-option disabled"><input type="radio" disabled> الدفع الإلكتروني <small>قريباً</small></label><button class="btn btn-gold full" type="submit">تأكيد الطلب · الدفع عند الاستلام</button></div><aside id="checkout-summary" class="summary"></aside></form>`;const update=()=>{const t=totals();$('#checkout-summary').innerHTML=`<h2>ملخص الطلب</h2>${t.items.map(i=>{const p=getProduct(i.id);return `<div><span>${p.name} × ${i.qty}</span><strong>${money(p.price*i.qty)}</strong></div>`}).join('')}<hr><div><span>التوصيل</span><strong>${money(t.ship)}</strong></div><div class="grand"><span>الإجمالي</span><strong>${money(t.total)}</strong></div>`};$('#city').addEventListener('change',update);update();$('#order-form').onsubmit=ev=>{ev.preventDefault();const data=new FormData(ev.target),order='NB-'+Date.now().toString().slice(-6);localStorage.removeItem(cartKey);e.innerHTML=`<div class="success-state"><div class="success-icon">✓</div><p class="eyebrow">تم استلام طلبك بنجاح</p><h1>شكراً لثقتك بنُبل</h1><p>سيتم التواصل معك قريباً لتأكيد تفاصيل التوصيل.</p><div class="order-number">رقم الطلب <strong>${order}</strong></div><p>الطلب باسم: <b>${data.get('name')}</b></p><a class="btn btn-gold" href="products.html">العودة للتسوق</a></div>`;updateCount()};}
updateCount();renderHome();renderProducts();renderDetail();renderCart();renderCheckout();
