export const products = [
  {id:'royal-oud',name:'Royal Oud',arabicName:'عود ملكي',price:299,oldPrice:349,size:'100ml',type:'شرقي',stock:'متوفر',rating:4.9,short:'فخامة شرقية بعمق لا يُنسى.',description:'تركيبة غنية تجمع بين العود الكمبودي الفاخر والزعفران والجلد الناعم. عطر للحضور الواثق والمناسبات التي تستحق أن تُخلّد.',notes:['عود كمبودي','زعفران','جلد','عنبر'],tone:'dark',badge:'الأكثر مبيعاً'},
  {id:'black-night',name:'Black Night',arabicName:'ليلة سوداء',price:199,oldPrice:229,size:'50ml',type:'خشبي',stock:'متوفر',rating:4.8,short:'غموض جذاب يرافقك حتى آخر الليل.',description:'مزيج ساحر من الفلفل الأسود والأرز والباتشولي، ينتهي بلمسة فانيلا دافئة تمنحك كاريزما لا تقاوم.',notes:['فلفل أسود','أرز','باتشولي','فانيلا'],tone:'black',badge:''},
  {id:'golden-rose',name:'Golden Rose',arabicName:'وردة ذهبية',price:249,oldPrice:279,size:'100ml',type:'زهري',stock:'متوفر',rating:4.7,short:'نعومة الورد بلمسة ذهبية مشرقة.',description:'ورود طازجة من قلب المغرب تلتقي بالبرغموت والمسك الأبيض في عطر أنثوي راقٍ، مشرق ومتوازن.',notes:['ورد مغربي','برغموت','ياسمين','مسك أبيض'],tone:'rose',badge:'جديد'},
  {id:'blue-ocean',name:'Blue Ocean',arabicName:'المحيط الأزرق',price:179,oldPrice:199,size:'50ml',type:'منعش',stock:'متوفر',rating:4.6,short:'انتعاش نقي كنسمة على شاطئ هادئ.',description:'نفحات بحرية منعشة مع الليمون واللافندر، قاعدة من الأخشاب البيضاء لعطر يومي مفعم بالحيوية.',notes:['ليمون','نفحات بحرية','لافندر','أخشاب بيضاء'],tone:'blue',badge:''},
  {id:'white-musk',name:'White Musk',arabicName:'مسك أبيض',price:129,oldPrice:149,size:'30ml',type:'زهري',stock:'متوفر',rating:4.8,short:'نظافة وأناقة تدوم طوال اليوم.',description:'مسك أبيض ناعم مع زهر البرتقال والقطن، اختيار مثالي لمن يحب العطور الهادئة والقريبة من البشرة.',notes:['مسك أبيض','زهر البرتقال','قطن','بودرة'],tone:'white',badge:'قيمة مميزة'},
  {id:'saffron-amber',name:'Saffron Amber',arabicName:'عنبر الزعفران',price:319,oldPrice:369,size:'100ml',type:'شرقي',stock:'قريباً',rating:4.9,short:'دفء العنبر مع توهج الزعفران.',description:'عطر شرقي غني، يبدأ بزعفران فاخر وينساب إلى عنبر حلو وخشب الصندل الدافئ.',notes:['زعفران','عنبر','صندل','فانيلا'],tone:'amber',badge:'قريباً'}
];
export const getProduct = id => products.find(p=>p.id===id);
export const money = value => `${value.toLocaleString('ar-MA')} MAD`;
export const productVisual = p => `<div class="product-visual tone-${p.tone}"><div class="mini-bottle"><span>NUːBL</span><b>${p.size}</b></div>${p.badge?`<small class="product-badge">${p.badge}</small>`:''}</div>`; 
export const card = p => `<article class="product-card">${productVisual(p)}<div class="card-body"><div class="card-top"><span class="type">${p.type}</span><span class="rating">★ ${p.rating}</span></div><h3>${p.name}</h3><p>${p.short}</p><div class="card-bottom"><strong>${money(p.price)}</strong><span>${p.size}</span></div><div class="card-actions"><a class="btn btn-dark" href="product.html?id=${p.id}">التفاصيل</a><button class="btn btn-gold add-to-cart" data-id="${p.id}" ${p.stock!=='متوفر'?'disabled':''}>أضف للسلة</button></div></div></article>`;
export const delivery = {casablanca:20,other:35};
